import { resolve } from "node:path";

/**
 * [SEC-H4] The safety backstop for the UNATTENDED dev pipeline (agent/query.ts) — retained
 * through the cc plan 4 permission overhaul (signed off 2026-08-13). Interactive sessions now
 * defer to CC's own permission engine with a human answering prompts; the pipeline has no human
 * in the loop and drives a third-party model (GLM) with Write/Edit/Bash enabled, so the only
 * safe default is to DENY anything this table flags and allow the rest. The table below is the
 * old repo-wide danger list, now scoped to (and owned by) this guard.
 *
 * `cwd` is the run's worktree; passed through so writes escaping it are treated as dangerous.
 */
interface DangerVerdict {
  danger: boolean;
  reason?: string;
}

const BASH_PATTERNS: [RegExp, string][] = [
  [/\brm\s+-[a-z]*r[a-z]*f|\brm\s+-[a-z]*f[a-z]*r/i, "recursive force remove (rm -rf)"],
  [/\bgit\s+push\b[^\n]*(--force(?!-with-lease)|\s-f\b)/i, "git force-push"],
  [/\bgit\s+reset\s+--hard\b/i, "git reset --hard"],
  [/\bgit\s+clean\s+-[a-z]*f/i, "git clean -f"],
  [/\b(drop\s+database|drop\s+table|truncate\s+table|delete\s+from)\b/i, "destructive SQL"],
  [/\b(npm|pnpm|yarn)\s+publish\b/i, "package publish"],
  [/\b(sudo|doas)\b/i, "privilege escalation"],
  [/:\s*\(\s*\)\s*\{[^}]*\}\s*;/, "fork bomb"],
  [/\bmkfs\b|\bdd\s+if=[^\n]*of=\/dev\//i, "raw disk write"],
  [/\bcurl\b[^\n]*\|\s*(sudo\s+)?(sh|bash|zsh)\b/i, "pipe-to-shell from network"],
];

const SECRET_PATH = /(^|\/)\.env(\.[a-z]+)?$|\/\.ssh\/|id_(rsa|ed25519)|(^|\/)credentials\b|\.pem$|\.p8$|\bsecrets?\b/i;

function isDangerous(toolName: string, input: Record<string, unknown>, cwd?: string): DangerVerdict {
  const command = typeof input.command === "string" ? input.command : "";

  if (toolName === "Bash" && command) {
    for (const [re, reason] of BASH_PATTERNS) {
      if (re.test(command)) return { danger: true, reason };
    }
  }

  // credential / secret paths across any tool that names a path
  const pathish = [input.file_path, input.path, input.notebook_path, command]
    .filter((x): x is string => typeof x === "string" && x.length > 0)
    .join(" ");
  if (SECRET_PATH.test(pathish)) return { danger: true, reason: "credential/secret path" };

  // writes resolving outside the session worktree — compare against cwd + "/" so a sibling dir
  // sharing the worktree's path prefix (…/sess-1 vs …/sess-1x) cannot slip through
  if (cwd && (toolName === "Write" || toolName === "Edit" || toolName === "NotebookEdit")) {
    const fp = input.file_path ?? input.notebook_path;
    if (typeof fp === "string" && fp.startsWith("/")) {
      const abs = resolve(fp);
      const root = resolve(cwd);
      if (abs !== root && !abs.startsWith(`${root}/`)) {
        return { danger: true, reason: "write outside the session worktree" };
      }
    }
  }

  return { danger: false };
}

export interface GuardVerdict {
  behavior: "allow" | "deny";
  reason: string;
}

export function pipelineGuardVerdict(
  tool: string,
  input: Record<string, unknown>,
  cwd?: string,
): GuardVerdict {
  const verdict = isDangerous(tool, input, cwd);
  if (verdict.danger) {
    return { behavior: "deny", reason: verdict.reason ?? "flagged by danger list" };
  }
  return { behavior: "allow", reason: "non-dangerous (pipeline auto-allow)" };
}

/**
 * Render the guard as a SELF-CONTAINED CC PreToolUse hook script (cc plan 7 task 5, signed off
 * 2026-08-13): the danger tables above are serialized into a standalone module that reads the
 * hook's stdin JSON and prints a permissionDecision — deny dangerous, allow the rest, no decision
 * for AskUserQuestion. `runCcQuery` writes this per run next to a `--settings` overlay; no daemon
 * HTTP round-trip, so one-shot callers need no session id or bearer. The allow verdicts matter as
 * much as the denies: a headless run has no human to answer CC's permission ask (plan mode's
 * `ExitPlanMode` included), so without this hook the spawn never reaches a terminal result.
 * Equivalence with `pipelineGuardVerdict` is pinned by test/unit/pipeline-guard.test.ts — change
 * verdict logic in BOTH places or the test fails.
 */
export function renderGuardHookScript(cwd?: string): string {
  const bash = JSON.stringify(BASH_PATTERNS.map(([re, reason]) => [re.source, re.flags, reason]));
  const secret = JSON.stringify([SECRET_PATH.source, SECRET_PATH.flags]);
  return `// GENERATED by anvild (agent/pipeline-guard.ts) — [SEC-H4] one-shot PreToolUse guard. Do not edit.
import { resolve } from "node:path";
const CWD = ${JSON.stringify(cwd ?? null)};
const BASH_PATTERNS = ${bash}.map(([s, f, r]) => [new RegExp(s, f), r]);
const SECRET = ${secret};
const SECRET_PATH = new RegExp(SECRET[0], SECRET[1]);
let raw = "";
process.stdin.setEncoding("utf8");
process.stdin.on("data", (c) => (raw += c));
process.stdin.on("end", () => {
  let tool = "";
  let input = {};
  try {
    const j = JSON.parse(raw);
    tool = String(j.tool_name ?? "");
    if (j.tool_input && typeof j.tool_input === "object") input = j.tool_input;
  } catch {}
  // AskUserQuestion has no answer path in an unattended run; emit no decision so CC's default applies.
  if (tool === "AskUserQuestion") {
    process.stdout.write("{}\\n");
    return;
  }
  const command = typeof input.command === "string" ? input.command : "";
  let danger = null;
  if (tool === "Bash" && command) {
    for (const [re, reason] of BASH_PATTERNS) {
      if (re.test(command)) { danger = reason; break; }
    }
  }
  if (!danger) {
    const pathish = [input.file_path, input.path, input.notebook_path, command]
      .filter((x) => typeof x === "string" && x.length > 0)
      .join(" ");
    if (SECRET_PATH.test(pathish)) danger = "credential/secret path";
  }
  if (!danger && CWD && (tool === "Write" || tool === "Edit" || tool === "NotebookEdit")) {
    const fp = input.file_path ?? input.notebook_path;
    if (typeof fp === "string" && fp.startsWith("/")) {
      const abs = resolve(fp);
      const root = resolve(CWD);
      if (abs !== root && !abs.startsWith(root + "/")) danger = "write outside the session worktree";
    }
  }
  const out = danger
    ? { permissionDecision: "deny", permissionDecisionReason: \`pipeline denied — \${danger}\` }
    : { permissionDecision: "allow", permissionDecisionReason: "non-dangerous (pipeline auto-allow)" };
  process.stdout.write(JSON.stringify({ hookSpecificOutput: { hookEventName: "PreToolUse", ...out } }) + "\\n");
});
`;
}

